import '../styles/globals.css';
import type { Metadata } from 'next';
import { Gowun_Batang } from 'next/font/google';

const GownBatang = Gowun_Batang ({
  subsets: ['latin'],
  weight: '700'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GownBatang.className}>{children}</body>
    </html>
  );
}
